import './entity/entity-death'
import './entity/entity-hit-effect'

/* these modules cannot export anything,
 * or else it might screw up import order
 * and therefore screw up binary encoding */
import './entity/dummy_DummyPlayer'
import './entity/ig_ENTITY_Effect'
import './entity/ig_ENTITY_PushPullBlock'
import './entity/ig_ENTITY_Switch'
import './entity/ig_ENTITY_OneTimeSwitch'
import './entity/ig_ENTITY_MultiHitSwitch'
import './entity/ig_ENTITY_WallHorizontal'
import './entity/ig_ENTITY_WallVertical'
import './entity/ig_ENTITY_OLPlatform'
import './entity/ig_ENTITY_Ball'
import './entity/sc_CombatProxyEntity'
import './entity/ig_ENTITY_Crosshair'
import './entity/ig_ENTITY_Enemy'
import './entity/ig_ENTITY_CombatantMarble'
import './entity/sc_ItemDropEntity'
import './entity/ig_ENTITY_Chest'
import './entity/ig_ENTITY_FloorSwitch'
import './entity/ig_ENTITY_NPC'
import './entity/ig_ENTITY_BounceBlock'
import './entity/ig_ENTITY_BounceSwitch'
import './entity/ig_ENTITY_Destructible'
import './entity/ig_ENTITY_EnemyCounter'
import './entity/ig_ENTITY_DynamicPlatform'
import './entity/ig_ENTITY_ItemDestruct'
import './entity/ig_ENTITY_XenoDialog'
import './entity/sc_PartyMemberEntity'
import './entity/ig_ENTITY_Prop'
import './entity/sc_FoodIconEntity'
import './entity/ig_ENTITY_Door'
import './entity/sc_BombEntity'
import './entity/ig_ENTITY_BombPanel'
import './entity/sc_FerroEntity'
